# Build and publish a node.js-based library in two jobs. Only attempt to
# publish anyhting to npm if the first job succeeded (so the build was ok)
# and a new tag was found.

pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run test
    displayName: 'Npm install and test'

  - task: Npm@1
    condition: eq(variables['build.sourceBranch'], 'refs/tags/*')
    inputs:
      command: publish
      publishEndpoint: npmjs.com
    displayName: 'Publishing to npmjs.com'
