# Build and publish a node.js-based library in two jobs. Only attempt to
# publish anyhting to npm if the first job succeeded (so the build was ok)
# and a new tag was found.

pool:
  vmImage: 'Ubuntu 16.04'

jobs:
- job: Test
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'
  - script: |
      npm install
      npm run test
    displayName: 'npm install, test, and build'

- job: Publish
  dependsOn: Test
  condition: and(succeeded('Test'), eq(variables['build.sourceBranch'], 'refs/tags/*'))
  steps:
  - task: Npm@1
    inputs:
      command: publish
      publishEndpoint: npmjs.com
